#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use AdamWojs\AwokadoRobot\AwokadoRobot;
use AdamWojs\AwokadoRobot\Notification\SlackWebhookTransportFactory;
use AdamWojs\AwokadoRobot\Menu\Provider\Awokado\AwokadoMenuProviderFactory;
use AdamWojs\AwokadoRobot\Menu\Provider\ZieloneTarasy\ZieloneTarasyMenuProviderFactory;
use AdamWojs\AwokadoRobot\LoggerFactory;

$restaurants = [
  'awokado' => AwokadoMenuProviderFactory::class,
  'zielone-tarasy' => ZieloneTarasyMenuProviderFactory::class
];


if ($argc < 3) {
    exit("usage: $argv[0] <restaurant> <webhook-url>");
}

$restaurant = $argv[1];
$webhook = $argv[2];


if(empty($restaurants[$restaurant])) {
    exit("unknown restaurant");
}

$menuProvider = $restaurants[$restaurant]::create();
$transport = SlackWebhookTransportFactory::create($webhook);

$robot = new AwokadoRobot($menuProvider, $transport);
$robot->setLogger(LoggerFactory::get());
$robot->run();
