#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use AdamWojs\AwokadoRobot\AwokadoRobot;
use AdamWojs\AwokadoRobot\MenuProvider;
use AdamWojs\AwokadoRobot\Notification\SlackWebhookTransport;
use Goutte\Client;
use GuzzleHttp\Client as GuzzleClient;

if ($argc < 2) {
    exit("usage: $argv[0] <webhook-url>");
}

$goutteClient = new Client();
$goutteClient->setClient(new GuzzleClient([
    'timeout' => 180,
]));

$menuProvider = new MenuProvider($goutteClient, 'http://awokado.krakow.pl/lunch-bar/menu/');
$transport = new SlackWebhookTransport(new GuzzleClient(), $argv[1]);

$robot = new AwokadoRobot($menuProvider, $transport);
$robot->run();




